server.port=8081
spring.application.name=auth-service
spring.datasource.url=${AUTH_DB_URL:jdbc:postgresql://127.0.0.1:5432/auth_db}
spring.datasource.username=${DB_USER:microapp}
spring.datasource.password=${DB_PASSWORD:microapp123}
